

service: todoapplication-backend


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2



functions:
  tasks:
    handler: handler.tasks
    environment:
      dataBaseHost: ${opt:dataBaseHost}
      dataBaseUser: ${opt:dataBaseUser}
      dataBasePassword: ${opt:dataBasePassword}
    events:
       - http:
          path: tasks
          method: get
          cors: true
       - http:
          path: tasks/{taskId}
          method: delete
          cors: true
       - http:
          path: tasks/{taskId}
          method: put
          cors: true   
       - http:
          path: tasks
          method: post
          cors: true 

